# Generated by Django 4.1.3 on 2022-11-30 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_classroom_table_alter_student_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('administration.student',),
        ),
    ]
