# Generated by Django 4.1.3 on 2022-11-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_teacherproxy_alter_studentproxy_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField()),
                ('date', models.DateField()),
                ('course', models.CharField(max_length=30)),
                ('tester', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('number_of_questions', models.IntegerField()),
                ('final_grade', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField()),
                ('date', models.DateField()),
                ('course', models.CharField(max_length=30)),
                ('tester', models.CharField(max_length=50)),
                ('project_title', models.CharField(max_length=100)),
                ('number_of_groups', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinalExamProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('administration.finalexam',),
        ),
        migrations.CreateModel(
            name='ProjectProxy',
            fields=[
            ],
            options={
                'ordering': ['project_title'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('administration.project',),
        ),
    ]
